### ISSUE TITLE
Not able to import

### ISSUE THREAD

**Issue by reckonsys** [dekatotoro/SlideMenuControllerSwift#43] opened 2015-06-15 12:02 UTC
when i import showing No such Module.

**Comment by htarwara6245** [comment] 2015-06-16 10:11
how do u import this library from cocoapods? or manual?

**Comment by reckonsys** [comment] 2015-06-16 13:27
from cocoapods

**Comment by htarwara6245** [comment] 2015-06-17 02:53
I think cocoapods is not fully supported yet.Even me,i have to import manually by copying SlideMenuController.swift to my project location.Please see for your self - https://github.com/dekatotoro/SlideMenuControllerSwift/issues/35 . Sometime due xcode 6.3 problem on large project,you might have to clean the whole project and try to rebuild again.

**Comment by reckonsys** [comment] 2015-06-17 04:21
I manually Copied but still not able to import

**Comment by reckonsys** [comment] 2015-06-17 10:51
May be some problem with file from SlideMenuController.

**Comment by htarwara6245** [comment] 2015-06-19 02:13
I guess not.I think there is something wrong with your project structure.If u want to be sure,try to create new project and import the SlideMenuViewController.swift manually into your project and use it because i have the same issue like yours which i cant install from cocoapods but,can import manually and work fine for now.

**Comment by dekatotoro** [comment] 2015-07-17 04:17
@reckonsys 
How do you try to do with the latest?

**Comment by reckonsys** [comment] 2015-07-22 05:11
i am not using it app.

**Comment by dekatotoro** [comment] 2015-11-12 14:05
Cocoapods is already fully supported.
Close this issue.

**Closed by dekatotoro** 2015-11-12 14:05 UTC

**Comment by kerimsari** [comment] 2016-03-06 11:27
Hello,

I've succesfully imported the SlideMenuController from cocoapods.

The problem is that i can not add right and left buttons with the method addRightBarButtonWithImage
and addLeftBarButtonWithImage

Please suggest...

**Comment by Pluto-Y** [comment] 2016-03-06 11:34
How did you import the SlideMenuController?

**Comment by kerimsari** [comment] 2016-03-06 11:39
Hello,

I've imported it with creating a podfile and pod install command.

**Comment by kerimsari** [comment] 2016-03-06 11:40
import UIKit
import SlideMenuControllerSwift


@UIApplicationMain
class AppDelegate: UIResponder ,UIApplicationDelegate {

    var window: UIWindow?
    
    func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
        // Override point for customization after application launch
        
        // create viewController code..
        let storyboard = UIStoryboard(name: "Main", bundle: NSBundle(identifier: "com.mobilentis.jetforme"))
            
        let mainViewController = storyboard.instantiateViewControllerWithIdentifier("MainViewController") as! MainViewController
        let leftViewController = storyboard.instantiateViewControllerWithIdentifier("MenuViewController") as! MenuViewController
            
        let slideMenuController = SlideMenuController(mainViewController: mainViewController, leftMenuViewController: leftViewController)
        
        self.window?.rootViewController = slideMenuController
    
        self.window?.makeKeyAndVisible()
            
        return true
    }

**Comment by Pluto-Y** [comment] 2016-03-06 11:46
I don't see the code you added the menu button.

**Comment by kerimsari** [comment] 2016-03-06 11:48
//
//  ViewController.swift
//  jetforme
//
//  Created by Elif on 03/03/16.
//  Copyright © 2016 Elif. All rights reserved.
//

import UIKit
import SlideMenuControllerSwift


class MainViewController: SlideMenuController {


    
    
    override func viewDidLoad() {
        super.viewDidLoad()
       
        
        self.view.addBackgroundImage()
   }
    
    override func awakeFromNib() {

        if let controller = self.storyboard?.instantiateViewControllerWithIdentifier("MenuViewController") {
            self.leftViewController = controller
        }
        
        super.awakeFromNib()
    }


    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    
    override func viewWillAppear(animated: Bool) {
        super.viewWillAppear(animated)
        
        addLeftBarButtonWithImage(UIImage(named: "ic_menu_black_24dp.png")!)
    }



}

**Comment by Pluto-Y** [comment] 2016-03-06 11:53
Yes, the left(or right) menu button are added in the navigationBar, but you don't use the UINavigationController.So when you add the menu is useless.

**Comment by kerimsari** [comment] 2016-03-06 11:55
Do you have a sample project this library?
It would be really helpfull?

**Comment by Pluto-Y** [comment] 2016-03-06 11:58
https://github.com/dekatotoro/SlideMenuControllerSwift/
This is the sample project and you can download it for references.

**Comment by kerimsari** [comment] 2016-03-06 12:01
I know this but this is not a sample project, this is the whole project I think?
No?

**Comment by Pluto-Y** [comment] 2016-03-06 12:05
Okay, I change the code you provided for you.
```
......
    let slideMenuController = SlideMenuController(mainViewController: mainViewController, leftMenuViewController: leftViewController)

    // Add this line
    let navController = UINavigationController(rootViewController: slideMenuController)
    // And change the rootViewController from slideMenuController into navController
    self.window?.rootViewController = navController
......
```

**Comment by kerimsari** [comment] 2016-03-06 12:14
Thank you very much...

**Comment by Pluto-Y** [comment] 2016-03-06 12:15
You are welcome.

**Comment by GaniduAsh** [comment] 2016-06-27 09:45
tried to copy file , still get the issue that , saying module not found , created a sample project event , still the same issue
